#!/bin/bash
#
# Copyright 2020 David Egan
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http:#www.apache.org/licenses/LICENSE-2.0
#
# Random Word Generator
# ---------------------
# Select a number of words from a specific library using a random number.
# The random number is sourced from `/dev/urandom` and corrected for modulo bias.
# By default, the library used is `/usr/share/dict/cracklib-small` which should be available on Ubuntu.
# -----------------------------------------------------------------------------------------------------------
THIS=$(readlink -f ${BASH_SOURCE[0]})
PROJECT_ROOT=$(dirname $THIS)
. "${PROJECT_ROOT}"/random.sh

function set_variables {
	readonly ALL_NON_RANDOM_WORDS=/usr/share/dict/cracklib-small
	KEYSPACE=$(sed -r '/[^A-Za-z]/d' ${ALL_NON_RANDOM_WORDS} | wc -l)
	NUM=$1
	ENTROPY=$(entropy $KEYSPACE $NUM)
}

# Entropy is defined as log base 2 of Character set to the power of the length.
# In this case, character set is the number of words available to select from and
# the length is the number of pseudorandom words output.
function entropy {
	export WORDSET=$1
	export WORDS=$2
	python3 - <<- EOF
	import math; import os;
	r = math.log(int(os.environ['WORDSET']) ** int(os.environ['WORDS']), 2)
	print(round(r, 2))
	EOF
}

function generate {
	X=0
	WORDS=""
	while [[ "$X" -lt "$1" ]]; do
		# Get a random number in the range [1..$KEYSPACE]
		random_number_in_range 1 $KEYSPACE
		WORD=$(sed -r '/[^A-Za-z]/d' $ALL_NON_RANDOM_WORDS | sed ${random_number}"q;d" | tr '[:upper:]' '[:lower:]')
		WORDS="${WORDS} ${WORD}"
		let "X = X + 1"
		echo "${X}: ${WORD}"
	done
	echo ""
	echo -e ${WORDS}
	echo ""
	echo "$1 words pseudo-randomly selected from a keyspace of ${KEYSPACE} words."
	echo "Total entropy of this passphrase is: ${ENTROPY}"
}

function main {
	echo "How many words?"
	read N
	if [[ -z $N ]]; then
		N=1
	fi
	set_variables $N
	generate $N
}

main
